version: 1.0.{build}
configuration: Release
os: Visual Studio 2015

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore  

build:
  project: KataPotter.sln
  parallel: true
  publish_wap: true
  verbosity: minimal

test_script:
- ps: >-
    .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:"KataPotter.Test\bin\debug\KataPotter.Test.dll" /resultsfile:unittest.trx" -filter:"+[*]*" -mergebyhash -output:"codecoveragereport.xml"