version: 1.0.{build}
configuration: Debug

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

environment:
  COVERALLS_REPO_TOKEN:
    secure: LcOESLld5nhbZol+zNyDAulUTDFm858DzyyoihtfsIqtubzhGhIo0W76lDj/9rAN 

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore  

build:
  project: KataPotter.sln
  parallel: true
  publish_wap: true
  verbosity: minimal

after_test: 
  # generate report for NUnit testing framework:
  - packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  KataPotter.Test\bin\Debug\KataPotter.Test.dll" -output:coverage.xml

  # generate report for MSTest testing framework:
  #    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:YOURPROJECT.Tests/bin/debug/YOURPROJECT.Tests.dll" -output:coverage.xml
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml  
