version: 1.0.{build}
configuration: Release

cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

environment:
  repo_token:
    secure: LcOESLld5nhbZol+zNyDAulUTDFm858DzyyoihtfsIqtubzhGhIo0W76lDj/9rAN 

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore  

build:
  project: KataPotter.sln
  parallel: true
  publish_wap: true
  verbosity: minimal

test_script:
  - .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe "-targetargs:""KataPotter.Test\bin\$env:CONFIGURATION\KataPotter.Test.dll"" /noshadow" -filter:"+[*]*" -output:opencoverCoverage.xml
  - .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover opencoverCoverage.xml
